import { useState } from 'react'
import { Check, ChevronRight, Eye, MailCheck, Monitor, Send, Smartphone } from 'lucide-react'
import ProjectIntro from '../components/ProjectIntro'
import { LumaLogo } from '../components/Logos'

const checks=['Asunto y preheader','Personalización','Enlaces y CTA','Contenido legal','Vista responsive','Proof aprobado']
export default function EmailStudio(){
  const [device,setDevice]=useState('desktop'),[done,setDone]=useState([]),[name,setName]=useState('Rossana'),[proof,setProof]=useState(false)
  const toggle=item=>setDone(items=>items.includes(item)?items.filter(x=>x!==item):[...items,item])
  return <main className="project-page luma-page"><ProjectIntro eyebrow="PROYECTO 05 · EMAIL & QA" title="Luma Email Studio" text="Un espacio de trabajo inspirado en el proceso de contenido, personalización, preview y quality assurance de AJO." tags={['React','QA','Responsive email','Personalización','AJO workflow']}><LumaLogo/></ProjectIntro>
      <section className="brand-site luma-site"><div className="studio-nav"><LumaLogo/><div className="breadcrumbs"><span>Campañas</span><ChevronRight/><b>Activación digital</b></div><button className="proof-button" onClick={()=>setProof(true)}><Send/> Enviar proof</button></div><div className="studio-workspace"><aside className="studio-sidebar"><span>CONTENIDO</span>{['Configuración','Email Designer','Personalización','Simular contenido','QA & Proof'].map((item,i)=><button className={i===4?'active':''} key={item}><i>{i<4?'✓':'5'}</i>{item}</button>)}<div className="ajo-note"><MailCheck/><b>Flujo AJO</b><p>Demo conceptual sin conexión a un sandbox empresarial.</p></div></aside><section className="studio-main"><header><div><small>EMAIL DESIGNER</small><h2>Revisión final de contenido</h2></div><div className="device-switch"><button className={device==='desktop'?'active':''} onClick={()=>setDevice('desktop')}><Monitor/></button><button className={device==='mobile'?'active':''} onClick={()=>setDevice('mobile')}><Smartphone/></button></div></header><div className={`email-canvas ${device}`}><article className="email-design"><div className="email-top">NovaBank <span>Área de clientes</span></div><div className="email-body"><span>Hola, {name || 'cliente'}</span><h2>Tu tarjeta digital ya está lista</h2><p>Actívala en pocos minutos y empieza a pagar desde tu móvil de forma cómoda y segura.</p><button>Activar mi tarjeta</button><div className="benefits"><b>Pago inmediato</b><b>Control desde la app</b><b>Activación segura</b></div></div><footer>Este es un email demostrativo · Privacidad · Darme de baja</footer></article></div></section><aside className="qa-panel"><div><Eye/><span>PREVISUALIZACIÓN</span></div><label>Nombre del test profile<input value={name} onChange={e=>setName(e.target.value)}/></label><h3>Checklist QA</h3><div className="qa-progress"><i style={{width:`${done.length/checks.length*100}%`}}></i></div><small>{done.length} de {checks.length} comprobaciones</small>{checks.map(item=><label className="check-row" key={item}><input type="checkbox" checked={done.includes(item)} onChange={()=>toggle(item)}/><i>{done.includes(item)?<Check/>:null}</i><span>{item}</span></label>)}<button className="approve-button" disabled={done.length!==checks.length}>{done.length===checks.length?'Email aprobado':'Completa la revisión'}</button></aside></div></section>{proof?<div className="modal-overlay" onClick={()=>setProof(false)}><div className="proof-modal" onClick={e=>e.stopPropagation()}><div><Send/></div><h2>Proof enviado</h2><p>La prueba se ha enviado al equipo de revisión. En AJO comprobaríamos también remitente, personalización y alertas antes de activar.</p><button onClick={()=>setProof(false)}>Entendido</button></div></div>:null}
  </main>
}
