import { useMemo, useState } from 'react'
import { CheckCircle2, FlaskConical, Info, RotateCcw, Trophy } from 'lucide-react'
import ProjectIntro from '../components/ProjectIntro'
import { OrbitLogo } from '../components/Logos'

const initial={a:{subject:'Activa tu tarjeta en pocos minutos',sent:5000,opens:2140,clicks:410},b:{subject:'Tu tarjeta digital ya está disponible',sent:5000,opens:1985,clicks:468}}
export default function ExperimentLab(){
  const [data,setData]=useState(initial),[goal,setGoal]=useState('CTR'),[calculated,setCalculated]=useState(false)
  const results=useMemo(()=>Object.fromEntries(Object.entries(data).map(([key,v])=>[key,{open:v.opens/v.sent*100,ctr:v.clicks/v.sent*100}])),[data])
  const winner=goal==='CTR'?(results.a.ctr>results.b.ctr?'A':'B'):(results.a.open>results.b.open?'A':'B')
  const update=(variant,field,value)=>setData(prev=>({...prev,[variant]:{...prev[variant],[field]:field==='subject'?value:Number(value)}}))
  return <main className="project-page orbit-page"><ProjectIntro eyebrow="PROYECTO 04 · OPTIMIZACIÓN" title="Orbit Experiment Lab" text="Una herramienta visual para plantear hipótesis, comparar tratamientos y explicar decisiones basadas en datos." tags={['React','useMemo','Formularios','A/B Testing','CRO']}><OrbitLogo/></ProjectIntro>
    <section className="brand-site orbit-site"><div className="lab-nav"><OrbitLogo/><span>Experimento / Email subject test</span><button onClick={()=>{setData(initial);setCalculated(false)}}><RotateCcw/> Reiniciar</button></div><div className="lab-layout"><aside className="lab-brief"><span className="step">01</span><h2>Define el experimento</h2><label>Hipótesis</label><textarea defaultValue="Un asunto centrado en disponibilidad generará más clics que uno centrado en rapidez."/><label>Métrica de éxito</label><select value={goal} onChange={e=>setGoal(e.target.value)}><option>CTR</option><option>Open rate</option></select><div className="info-box"><Info/><p>Una prueba real requiere tamaño de muestra suficiente, tiempo estable y significancia estadística.</p></div></aside><div className="variants-area"><div className="variants-heading"><div><span className="step">02</span><h2>Compara las variantes</h2></div><span className="audience-pill">50% A · 50% B</span></div><div className="variant-grid">{['a','b'].map(key=><article className={`variant-card ${calculated&&winner===key.toUpperCase()?'winner':''}`} key={key}>{calculated&&winner===key.toUpperCase()?<div className="winner-ribbon"><Trophy/> Ganadora</div>:null}<span>VARIANTE {key.toUpperCase()}</span><label>Asunto</label><input value={data[key].subject} onChange={e=>update(key,'subject',e.target.value)}/><div className="email-mini"><small>novabank</small><b>{data[key].subject}</b><p>Hola, Rossana. Tu tarjeta digital ya está lista...</p></div><div className="number-grid"><label>Envíos<input type="number" value={data[key].sent} onChange={e=>update(key,'sent',e.target.value)}/></label><label>Aperturas<input type="number" value={data[key].opens} onChange={e=>update(key,'opens',e.target.value)}/></label><label>Clics<input type="number" value={data[key].clicks} onChange={e=>update(key,'clicks',e.target.value)}/></label></div>{calculated?<div className="rates"><div><span>OPEN RATE</span><b>{results[key].open.toFixed(1)}%</b></div><div><span>CTR</span><b>{results[key].ctr.toFixed(1)}%</b></div></div>:null}</article>)}</div><button className="calculate-button" onClick={()=>setCalculated(true)}><FlaskConical/> Analizar experimento</button>{calculated?<div className="conclusion"><CheckCircle2/><div><b>La variante {winner} obtiene el mejor {goal}.</b><p>Esta demo calcula tasas. Antes de tomar una decisión real comprobaríamos significancia estadística y calidad de la muestra.</p></div></div>:null}</div></div></section>
  </main>
}
