import { useState } from 'react'
import { ArrowUpRight, Bell, ChevronDown, Mail, MousePointerClick, Send, Users } from 'lucide-react'
import ProjectIntro from '../components/ProjectIntro'
import { NexoLogo } from '../components/Logos'

const weeks={Semana:[42,58,47,72,66,82,75],Mes:[35,49,58,52,74,81,88],Trimestre:[28,40,53,67,61,79,92]}
export default function NexoDashboard(){
  const [period,setPeriod]=useState('Semana'),[metric,setMetric]=useState('Aperturas')
  return <main className="project-page nexo-page"><ProjectIntro eyebrow="PROYECTO 03 · DATA & MARKETING" title="Nexo Insights" text="Dashboard para observar el customer journey, interpretar campañas y convertir datos en decisiones." tags={['React','Datos','Dashboard','CSS Grid','AJO Reporting']}><NexoLogo/></ProjectIntro>
    <section className="brand-site nexo-site"><aside className="dash-sidebar"><NexoLogo/><nav><a className="active">Resumen</a><a>Campañas</a><a>Audiencias</a><a>Journeys</a><a>Experimentos</a></nav><div className="user-chip"><i>RM</i><span>Rossana M.<small>Marketing team</small></span></div></aside><div className="dash-main"><header><div><small>BUENOS DÍAS, ROSSANA</small><h2>Rendimiento general</h2></div><div><button className="dash-icon"><Bell/></button><select value={period} onChange={e=>setPeriod(e.target.value)}><option>Semana</option><option>Mes</option><option>Trimestre</option></select></div></header>
      <div className="dashboard-kpis"><article><div className="kpi-icon mint"><Send/></div><span>Emails entregados</span><strong>48.920</strong><small><b>↑ 12,4%</b> vs. periodo anterior</small></article><article><div className="kpi-icon peach"><Mail/></div><span>Open rate</span><strong>42,8%</strong><small><b>↑ 5,2%</b> por encima de media</small></article><article><div className="kpi-icon lilac"><MousePointerClick/></div><span>CTR</span><strong>7,6%</strong><small><b>↑ 1,3%</b> esta semana</small></article><article><div className="kpi-icon yellow"><Users/></div><span>Conversiones</span><strong>1.663</strong><small><b>↑ 8,9%</b> objetivo cumplido</small></article></div>
      <div className="dashboard-content"><article className="chart-panel"><div className="panel-heading"><div><small>EVOLUCIÓN</small><h3>{metric}</h3></div><select value={metric} onChange={e=>setMetric(e.target.value)}><option>Aperturas</option><option>Clics</option><option>Conversiones</option></select></div><div className="line-chart"><div className="chart-lines"><i></i><i></i><i></i><i></i></div><div className="chart-bars">{weeks[period].map((value,i)=><div key={i}><span style={{height:`${value}%`}}><b>{value}%</b></span><small>{['L','M','X','J','V','S','D'][i]}</small></div>)}</div></div></article><article className="journey-panel"><div className="panel-heading"><div><small>JOURNEY ACTIVO</small><h3>Activa tu tarjeta</h3></div><button>•••</button></div><div className="journey-flow"><div className="done"><i>✓</i><span>Audiencia elegible<small>12.480 perfiles</small></span></div><b></b><div className="done"><i>✓</i><span>Email inicial<small>98,4% entregado</small></span></div><b></b><div className="current"><i>48h</i><span>Espera<small>En proceso</small></span></div><b></b><div><i>?</i><span>Condición<small>Activación</small></span></div></div><button className="view-report">Ver informe completo <ArrowUpRight/></button></article></div>
    </div></section>
  </main>
}
